---
- name: Demonstrate variables
  hosts: localhost
  become: true
  remote_user: ansible
  vars_files:
   - vars/prod_user.yml
  vars:
   u1_name: db2
  tasks:
   - name: include variables
  # Include_vars overrides var_files
     include_vars: vars/dev_user.yml
   - name: task to create a user
     debug:
      msg: "{{u1_name}}" 
...