---
- name: play to demonstrate lookup plugin
#we read the file content using lookup plugin
  hosts: localhost
  gather_facts: no
  remote_user: ansible
  become: true
  vars:
   myvar: "{{lookup('file','/etc/passwd')}}"
  tasks:
   - name: Task to print the file content using lookup plugin.
     #using debug module to print the variable content
     debug:
      msg: "{{myvar}}"
...
#End
