---
- name: Create a user and add ssh public key to user's authorized keys
  hosts: localhost
  become: true
  remote_user: jenkins
  tasks:
   - name: Add a user
     user:
       name: asian01
       password: "{{ 'test123' | password_hash('sha512')}}"
       state: present
   
...
