---
- name: Demonstarate replace module in ansible
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: Task to replace the text using replace module
     replace:
       path: /etc/iscsi/initiatorname.iscsi
       regexp: iqn.2024-06.in.myclass.sivakumar:initclient
       replace: iqn.2024-06.in.myclass.sivakumar:myreplace
       backup: yes
...