---
- name: Play to replace PermitRootLogin in /etc/ssh/sshd_config file
  hosts: [ 192.168.1.98 ]
  become: true
  remote_user: ansible
  tasks:
   - name: Replace PermitRootLogin
     lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^PermitRootLogin #Regular Expression to search for this test, begining line; thats why cap symbol
      line: "PermitRootLogin no" #replace line with
      backup: yes #take file backup before doing changes
   - name: Restart the ssh service after the config 
     service:
      name: sshd
      state: restarted
...
# End of the play