---
- name: Demonstarate module to print something on the screen
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: print some text
     debug:
       msg: "Hello there... this is being printed by debug module"
...