---
- name: Demonstrate a play where as a task is forced to change status
  hosts: localhost
  become: true
  remote_user: ansible
  tasks: 
   - name: Task1 to print a message
     debug: 
      msg: This is message
     changed_when: true
     notify: handleme2
 #Handler is processed with notify statement when change occurs in the tasks
 #If no change occurs, handler will be ignored ie handler will not be notified
   - name: Task2 to print a message
     debug: 
      msg: This is message
     changed_when: true
     notify: handleme1 
  #Thisis second time you are notifying the same handler.
  #However, through you notify handler manytimes, it runs only once.
  #Handler are invoked at the end of all tasks processed
  #They are processed in the same order they appear in the handlers section and
  #not in the order they are notified    
  handler:
   - name: handleme
     debug:
      msg: In handler named handleme1
   - name: handleme
     debug:
      msg: In handler named handleme2    
...