---
- name: play to install http web server
  hosts: all
  remote_user: ansible
  become: true
  tasks:
   - name: task to copy repo file from local to remote server
     copy:
      src: /etc/yum.repos.d/rhel83.repo
      dest: /etc/yum.repos.d/rhel83.repo
      mode: '0644'
      owner: root
      group: root
   - name: task to install httpd package on remote server 
     yum:
      name: httpd
      state: installed
   - name: task to create a index file
     copy:
      src: /home/ansible/playbooks/index.html
      dest: /var/www/html/index.html
      mode: '0644'
      owner: root
      group: root
   - name: to start a firewalld demamon
     service:
      name: firewalld
      state: started
      enabled: yes
   - name: to add http port to firewall
     firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: yes
   - name: task to start http web server
     service:
      name: httpd
      state: started
      enabled: yes
...      






