---
- name: Play to demonstarte variable in debug module
# Run this play with -e option
# example Ansible-playbook -e eye_color=red play33.yml
# where -e : External variable. This will have higher precedence
# Compared local variables defined in the play
  hosts: localhost
  vars:
   eye_color: blue
  tasks:
   - name: task to debug a variable
     debug:
      var: eye_color
...