---
- name: Play to modify /etc/hosts file
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: Task to edit hosts file using lineinfile module
     lineinfile:
      path: /etc/hosts
      line: "192.168.1.25   vcenter.alclabs.in
           \n192.168.1.1    gateway.alclabs.in"
           #Appends the line at the end of the file. This default behaviour of lineinfile module
...
# End of the play