---
- name: Play to demonstrate anisble facts
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: print ansible facts using debug module
     debug:
      msg: |
           The kernel is "{{ansible_facts['kernel']}}" 
           and hostname is "{{ansible_facts['hostname']}}"
           and custom fact is "{{ansible_local['sap_prod']['sap']['myapp']}}"
...