---
- name: Play to demonstrate handler
  hosts: 192.168.1.77
  become: true
  remote_user: ansible
  vars:
   pkg_name: httpd
   src_name: httpd
   port: 99
  tasks: 
  - name: Install {{pkg_name}} in {ansible_hostname}
    yum: 
     name: "{{pkg_name}}"
     state: latest
    notify: web_start 
  - name: Copy the configuration file
    copy:
     src: /home/asible/playbooks/myweb.conf
     dest: /etc/httpd/conf.d/myweb.conf
    notify: web_restart 
  - name: create index.html  
    copy:
     connect: "<html><hi>Sample Page</hi></html>"
  - name: Add {{pport}} to firewall
    firewalld:
     port: "{{port}}" 
     permanent: yes
     immediate: yes
     state: enabled
  handlers: 
  - name: web_start
    service:
     name: "{{src_name}}"   
     state: started
  - name: Web_restart
    service:
     name: "{{src_name}}"
     state: restarted
...   


