---
#Commonly used magic variables:
#-----------------------------
#hostvars: You can access variables defined by any host in the play
#groups: Print the dictionary or map with all groups in inventory and each group
#has the list of hosts that belongs to it.
#group_names: List groups the current host is part of
#inventory_hostname: Iventory name of the current host being iterated over in the play
- name: play to demonstrate magic variables
  hosts: [ 192.168.1.31, 192.168.1.32 ]
  become: true
  tasks:
  # - name: print groups
  #   debug:
  #    var: groups
   - name: print inventory_hostname
     debug:
      var: inventory_hostname
  # - name: print group_names
  #   debug:
  #    var: group_names
  # - name: print hostvars
  #   debug:
  #    var: hostvars
...