---
- name: Play to retrieve system information 
  hosts: all
  become: true
  remote_user: ansible
  tasks:
 #  - name: Task to delete if the file exists, so that a new file will be created
 #    file:
 #     path: "/tmp/sysinfo_{{ansible_hostname}}"
 #     state: absent
   - name: Task to extract system information into a file
     lineinfile:
      path: "/tmp/sysinfo_{{ansible_hostname}}"
      line: "Name: {{ansible_hostname}} \nMemory: {{ansible_memtotal_mb}} \nCPU Count: 
             {{ansible_processor_count}}"
      create: yes #create file if it doesnt exists
   - name: Task to extract File System Mount information
     lineinfile:
      path: "/tmp/sysinfo_{{ansible_hostname}}"
      line: "{{item.mount}}"
     loop: "{{ansible_mounts}}"
   - name: Downlod the info file to control node 
     fetch:
      src: "/tmp/sysinfo_{{ansible_hostname}}"
      dest: "/sysInfo/sysinfo_{{ansible_hostname}}"
      flat: yes
...
      