---
- name: Play to demonstrate handlers
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   pkg_name: nfs-utils
   src_name: nfs-server
   status: started
  taska:
   - name: "Install {{pkg_name}} in {{ansible_hostname}}"
     yum:
      name: "{{pkg_name}}"
      state: latest
     notify: start_nfs
     handlers:
      - name: start_nfs
        service:
         name: "{{src_name}}"
         state: "{{status}}"
...
#End. 