---
- name: play to read CSV file
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   fname: /home/ansible/playbooks/sapulist.csv
  tasks:
   - name: Read {{fname}} using read_csv module
     read_csv:
      path: "{{fname}}"
     register: out
   - name: Print the file content
     debug:
      var: out
...
#End